### ISSUE TITLE
do not have same dependency in dependencies and peerDependencies

### ISSUE THREAD

**Issue by vvakame** [Bartvds/minitable#2]
detail https://github.com/npm/npm/issues/6506#issuecomment-63883598

**Comment by IgorMinar** [comment]
I sent a PR for this. The reason why fixing this is important is that npm fails and complains about this package.json when shrinkwrapping a project that uses minitable directly or as a transitive dependency.

So any project that depends on minitable directly or transitively needs to manually tweak the minitable package.json during each npm upgrade and re-shrinkwrap.

Since `tsd` (typescript type definition manager) depends on minitable, any typescript + npm project that shrinkwraps dependencies is affected.

Please merge #3  and cut a new version so that we can get tsd to update.
